### ISSUE TITLE
Language change not possible

### ISSUE THREAD

**Issue by MayerMooBox** [studer-raimann/docker-ilias#1]
I have installed Ilias version 5.3.7 with Mysql 5.7 from the Docker image sturai/ilias.
It is not possible to install a new language in the web interfast. The following error appears:

"Data for module 'adve' of language 'de' is not correctly saved. Please check the collation of your database tables lng_data and lng_modules. It must be utf8_unicode_ci."

Also some strings in the web interface are not displayed correctly. For example if I create a test in the menu the text "-assQuestions-" is displayed instead of "Questions".

I think that both issues belong to the same problem.

**Comment by corro** [comment]
Hi @MayerMooBox, thank you for your report. Indeed, ILIAS requires a specific database collation setting according to the [installation guide](https://www.ilias.de/docu/goto_docu_lm_367.html) (section "Database Installation/Configuration").

In order to set the default character set and collation, we must pass certain arguments to the `mysqld` command of the MySQL image. The example `stack.yml` must therefore contain the following `command` section:
```
[...]
    mysql:
        image: mysql:5.7
        command: |
            --character-set-server=utf8
            --collation-server=utf8_general_ci
[...]
```

I have updated the example in [Docker Hub Page](https://hub.docker.com/r/sturai/ilias/).

**Comment by MayerMooBox** [comment]
Many thanks for that quick response!

I made the changes you have described and it is working now as expected.

Thank you.
